// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: query_process.proto

package io.grpc.examples.queryprocess;

public interface DataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:queryprocess.Data)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string raw_dsl = 1;</code>
   * @return The rawDsl.
   */
  String getRawDsl();
  /**
   * <code>string raw_dsl = 1;</code>
   * @return The bytes for rawDsl.
   */
  com.google.protobuf.ByteString
      getRawDslBytes();
}
