// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: query_process.proto

package io.grpc.examples.queryprocess;

public interface QpRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:queryprocess.QpRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string query = 1;</code>
   * @return The query.
   */
  String getQuery();
  /**
   * <code>string query = 1;</code>
   * @return The bytes for query.
   */
  com.google.protobuf.ByteString
      getQueryBytes();
}
