// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: query_process.proto

package io.grpc.examples.queryprocess;

public final class QueryProcessProto {
  private QueryProcessProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_queryprocess_QpRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_queryprocess_QpRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_queryprocess_QpResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_queryprocess_QpResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_queryprocess_Data_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_queryprocess_Data_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023query_process.proto\022\014queryprocess\"\032\n\tQ" +
      "pRequest\022\r\n\005query\030\001 \001(\t\"I\n\nQpResponse\022\014\n" +
      "\004code\030\001 \001(\005\022 \n\004data\030\002 \001(\0132\022.queryprocess" +
      ".Data\022\013\n\003msg\030\003 \001(\t\"\027\n\004Data\022\017\n\007raw_dsl\030\001 " +
      "\001(\t2R\n\020QueryProcessGrpc\022>\n\007Process\022\027.que" +
      "ryprocess.QpRequest\032\030.queryprocess.QpRes" +
      "ponse\"\000B9\n\035io.grpc.examples.queryprocess" +
      "B\021QueryProcessProtoP\001\242\002\002QPb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_queryprocess_QpRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_queryprocess_QpRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_queryprocess_QpRequest_descriptor,
        new String[] { "Query", });
    internal_static_queryprocess_QpResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_queryprocess_QpResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_queryprocess_QpResponse_descriptor,
        new String[] { "Code", "Data", "Msg", });
    internal_static_queryprocess_Data_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_queryprocess_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_queryprocess_Data_descriptor,
        new String[] { "RawDsl", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
